# Generated by Django 5.0.6 on 2024-06-19 10:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_instructorprofile_studentprofile_delete_swap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='purchase_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.purchase'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 13, 40, 0, 295824)),
        ),
    ]
