# Generated by Django 5.0.6 on 2024-06-19 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_meeting_purchase_id_purchase_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_path',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 14, 15, 47, 356981)),
        ),
    ]
