# Generated by Django 5.0.6 on 2024-06-19 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_meeting_date_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_icon_url',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 14, 42, 6, 711148)),
        ),
    ]
