# Generated by Django 5.0.6 on 2024-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_category_image_path_alter_meeting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='purchase_id',
            new_name='purchase',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(default='WaitingInstructor', max_length=20),
        ),
    ]
