# Generated by Django 5.0.6 on 2024-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_purchase_id_meeting_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
