# Generated by Django 5.0.6 on 2024-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_meeting_purchase_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='video_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
